export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const GET_POSTS_BEGIN = 'GET_POSTS_BEGIN'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR'

export const GET_POST_BEGIN = 'GET_POST_BEGIN'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_ERROR = 'GET_POST_ERROR'

export const ADD_POST_BEGIN = 'ADD_POST_BEGIN'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_ERROR = 'ADD_POST_ERROR'
